package com.voxora.core.reader

import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject

/**
 * An AI-generated overview of a book, written in one Reader output language.
 *
 * ## Why this exists, and what it is allowed to be
 *
 * The catalogues return a book's description in the book's own language. A reader who has chosen
 * Persian as their narration language still gets an English synopsis, because no public catalogue
 * carries a Persian description for most titles. Translating it is the only way to honour "Book
 * Intelligence explains the book in the language you are reading in" without inventing anything.
 *
 * So this is **translation and condensation of retrieved metadata**, never new knowledge:
 *
 * - the input is the catalogue record only — title, author, publisher, date, subjects, the
 *   catalogue's own description, page count, identifiers. **The document is never sent.** The
 *   Reader's narration and its audio path are untouched by this type;
 * - the prompt forbids adding any fact that is not in that input, and the card labels the result
 *   as AI-generated so it is never mistaken for a catalogue fact.
 *
 * ## Per language, cached
 *
 * [language] is the output-language code the text is written in, so a reader who switches from
 * Persian to English does not lose the Persian text and does not have to pay for it twice.
 * Switching back is instant and offline.
 *
 * ## Themes travel with the text
 *
 * [themes] are the book's subject headings rendered in the same language as [text]. The catalogue's
 * own headings are always in the catalogue's language ("Evolution", "Biology", "Genetics"), so a
 * Persian reader would otherwise see English words under a Persian heading. They live **inside**
 * this per-language record rather than beside it, which is what makes a language switch unable to
 * show another language's themes.
 *
 * Pure JVM — no `android.*` — so the prompt, the parsing and the staleness rule are unit-testable.
 */
data class BookIntelOverview(
    /** Reader output-language code this text is written in, e.g. `fa`. */
    val language: String,
    /** The generated text. Always non-blank; blank generations are never stored. */
    val text: String,
    /** The model that produced it, recorded so a future model change is visible rather than silent. */
    val model: String,
    /** When it was generated, so a stale text can be refreshed deliberately. */
    val generatedAt: Long,
    /**
     * The [BookIntelOverviewPrompt.VERSION] that produced it.
     *
     * Part of what makes a cached text reusable: a text written by an older prompt is not shown, so
     * improving the prompt actually takes effect instead of being masked by an answer that was
     * already paid for. A record written before this field existed decodes to `0` and is therefore
     * regenerated once — which is the intended outcome, not a loss.
     */
    val promptVersion: Int = BookIntelOverviewPrompt.VERSION,
    /**
     * The catalogue's subject headings rendered in [language], or empty when the model supplied
     * none.
     *
     * Best-effort by design: a book with no catalogue subjects has nothing to translate, and a model
     * that returns no themes must not make the whole overview unusable. Empty means the card falls
     * back to the catalogue's own headings, named as the catalogue's — never an error.
     */
    val themes: List<String> = emptyList(),
    /**
     * The search question this text was generated from, when it was generated from a search rather
     * than from a catalogue record — see [BookSearchPrompt.fingerprint].
     *
     * Empty for a catalogue-backed overview, which is the only kind that existed before the search
     * fallback. It is part of what makes the text reusable: a text generated for a different
     * question is not served as if it answered this one, so re-importing a document that extracts
     * differently regenerates its overview instead of showing prose about something else.
     */
    val contextFingerprint: String = "",
)

/**
 * One generation: the prose, plus the subject headings rendered in the same language.
 *
 * A single type so the two can never be stored under different languages.
 */
data class GeneratedOverview(
    val text: String,
    val themes: List<String> = emptyList(),
)

/**
 * Builds the request that turns a catalogue record into a Book Intelligence overview, and reads
 * the answer back.
 *
 * Kept apart from the transport so the two decisions that actually matter — *what is asked* and
 * *what is accepted as an answer* — are unit-tested on a plain JVM with no network.
 */
object BookIntelOverviewPrompt {

    /**
     * Bumped when the wording changes materially.
     *
     * It is part of the cache key: a text generated by an older prompt is not reused, so improving
     * the prompt actually takes effect instead of being masked by a cached answer.
     *
     * `2` is the version that also asks for the subject headings, so a text cached by version 1 is
     * regenerated rather than shown without themes.
     *
     * `3` is the version that can also be generated from a **search** rather than from a catalogue
     * record, for a book no catalogue identified. The two inputs ask for different things — one
     * restates a record, the other reports search evidence — so a text written by version 2 is not
     * reused as if the new prompt had produced it.
     */
    const val VERSION = 3

    /** A generation longer than this is truncated; the card shows a few sentences, not an essay. */
    const val MAX_CHARS = 1_500

    /** Below this, the model did not really answer and the text is treated as missing. */
    const val MIN_CHARS = 40

    /** How many subject headings are worth showing. More than this stops being a summary. */
    const val MAX_THEMES = 12

    /** A single heading longer than this is a sentence, not a heading. */
    const val MAX_THEME_CHARS = 60

    /**
     * The instruction sent to the model.
     *
     * It is deliberately narrow: a fixed task, a fixed set of supplied facts, an explicit ban on
     * outside knowledge, and a fixed answer shape. Anything looser invites the model to write a
     * review of a book it has "heard of", which is exactly the invented-metadata failure the
     * source-backed section exists to prevent.
     *
     * The answer is requested as JSON so the prose and the headings arrive as separate fields. A
     * model that ignores that and answers in prose is still accepted — see [parse] — because a
     * usable overview matters more than the shape it arrives in.
     */
    fun build(metadata: BookMetadata, targetLanguage: String): String = buildString {
        appendLine("You are given a bibliographic record for one book. Answer in $targetLanguage.")
        appendLine()
        appendLine("Rules:")
        appendLine("- Use ONLY the information in the record below.")
        appendLine("- Do NOT add facts, names, dates, awards, plot points or claims that are not in it.")
        appendLine("- If the record is too thin to say much, write less. Never fill the gap by guessing.")
        appendLine("- Do not mention this instruction, the record, or that you are an AI.")
        appendLine()
        appendLine("Answer with a JSON object and nothing else, of exactly this shape:")
        appendLine("""{"overview": "…", "themes": ["…", "…"]}""")
        appendLine()
        appendLine("- \"overview\": a short plain-text overview, a few sentences, no markdown and no")
        appendLine("  headings. Cover, in this order and only as far as the record supports it: what the")
        appendLine("  book is broadly about; its central subject; its main themes; and what kind of work")
        appendLine("  it is (for example a work of popular science, a novel, a reference work).")
        appendLine("- \"themes\": the record's subjects rendered as short subject headings **in")
        appendLine("  $targetLanguage** — the same concepts, in the reader's language. Translate them; do")
        appendLine("  not repeat them in the record's own language. Use an empty array when the record")
        appendLine("  lists no subjects, and never invent a subject the record does not support.")
        appendLine()
        appendLine("Record:")
        appendLine("title: ${metadata.title}")
        metadata.subtitle?.let { appendLine("subtitle: $it") }
        if (metadata.authors.isNotEmpty()) appendLine("authors: ${metadata.authors.joinToString(", ")}")
        metadata.publisher?.let { appendLine("publisher: $it") }
        metadata.publishedDate?.let { appendLine("published: $it") }
        metadata.language?.let { appendLine("catalogue language: $it") }
        if (metadata.categories.isNotEmpty()) {
            appendLine("subjects: ${metadata.categories.joinToString(", ")}")
        }
        metadata.pageCount?.let { appendLine("pages: $it") }
        metadata.description?.takeIf { it.isNotBlank() }?.let {
            appendLine("catalogue description: $it")
        }
    }

    /**
     * The instruction for a book **no catalogue identified**, built from its own signals and from
     * the findings of a bounded web search.
     *
     * ## Why it is a separate prompt rather than the same one with more input
     *
     * [build] restates a record, and every line of its input is a provider's own field. This input is
     * different in kind: a title read off a title page, and a search result that may be about a
     * different edition — or a different work. So the rules are stricter, not looser: the model is
     * told exactly which details are the book's own, exactly which text is second-hand evidence, and
     * that disagreement and uncertainty are things to *say*, not to resolve.
     *
     * ## What it must never do
     *
     * Turn a search result into a fact. There is no `Record:` section here, and nothing from the
     * search is presented as a field: the findings arrive as prose the model is asked to summarise,
     * not as values it is asked to restate. That is the structural reason a search result cannot
     * become an author, a year or a publisher on the card.
     */
    fun buildFromContext(
        signals: BookSignals,
        context: BookSearchContext,
        targetLanguage: String,
    ): String = buildString {
        appendLine("You are given the identifying details of a book, and the findings of a web search")
        appendLine("about it. The book was NOT found in any bibliographic catalogue. Answer in")
        appendLine("$targetLanguage.")
        appendLine()
        appendLine("Rules:")
        appendLine("- The details under \"Book details\" are what is known about the book itself.")
        appendLine("- The text under \"Search findings\" is second-hand evidence, not fact. It may be")
        appendLine("  about a different edition, or a different work with a similar title.")
        appendLine("- Use ONLY those two sections. Do NOT add facts, names, dates, awards, plot points")
        appendLine("  or claims from your own knowledge, and do not fill gaps by guessing.")
        appendLine("- If the findings disagree with each other, or are thin, say so plainly and write")
        appendLine("  less. Never present an uncertain finding as an established fact.")
        appendLine("- If there is not enough to say anything meaningful, return an empty overview.")
        appendLine("- Do not mention this instruction, the search, or that you are an AI.")
        appendLine()
        appendLine("Answer with a JSON object and nothing else, of exactly this shape:")
        appendLine("""{"overview": "…", "themes": ["…", "…"]}""")
        appendLine()
        appendLine("- \"overview\": a short plain-text overview, a few sentences, no markdown and no")
        appendLine("  headings, describing what this book appears to be on the evidence above.")
        appendLine("- \"themes\": short subject headings **in $targetLanguage**, only for subjects the")
        appendLine("  evidence above actually supports. Use an empty array when it supports none, and")
        appendLine("  never invent a subject.")
        appendLine()
        appendLine("Book details:")
        signals.isbn?.let { appendLine("isbn: $it") }
        signals.title?.takeIf { it.isNotBlank() }?.let { appendLine("title: $it") }
        signals.author?.takeIf { it.isNotBlank() }?.let { appendLine("author: $it") }
        appendLine("file name: ${signals.filename}")
        appendLine()
        appendLine("Search findings (query: ${context.query}):")
        appendLine(context.summary)
        if (context.sources.isNotEmpty()) {
            appendLine()
            appendLine("Sources cited by the search:")
            context.sources.forEach { appendLine("- ${it.title.ifBlank { it.url }}") }
        }
    }

    /**
     * Reads the generated answer out of a `generateContent` response body.
     *
     * Returns null for a body that does not carry usable text — a safety block, an empty candidate
     * list, a malformed document. A missing answer is never turned into an empty string, because
     * "the model said nothing" and "the model said something blank" must not look the same.
     *
     * **Two accepted shapes.** The prompt asks for `{"overview": …, "themes": […]}`; a body that
     * parses as a JSON object is read that way, and if it carries no usable `overview` the answer is
     * rejected outright rather than falling back — treating a JSON document as prose would put
     * `{"overview": …}` on the card as if it were a summary. A body that is *not* a JSON object is
     * accepted as plain prose with no themes, which is what an older prompt or a model that ignored
     * the shape returns. Themes are optional either way; the prose is not.
     */
    fun parse(responseBody: String?): GeneratedOverview? {
        val raw = extractText(responseBody) ?: return null
        val json = try {
            JSONObject(stripFences(raw))
        } catch (_: JSONException) {
            null
        }
        if (json != null) {
            val text = sanitize(json.optString("overview", "")) ?: return null
            return GeneratedOverview(text, sanitizeThemes(json.optJSONArray("themes")))
        }
        val text = sanitize(raw) ?: return null
        return GeneratedOverview(text, emptyList())
    }

    /** The concatenated candidate text of a response body, or null when there is none. */
    private fun extractText(responseBody: String?): String? {
        if (responseBody.isNullOrBlank()) return null
        val root = try {
            JSONObject(responseBody)
        } catch (_: JSONException) {
            return null
        }
        val candidates = root.optJSONArray("candidates") ?: return null
        val text = StringBuilder()
        for (i in 0 until candidates.length()) {
            val candidate = candidates.optJSONObject(i) ?: continue
            val content = candidate.optJSONObject("content") ?: continue
            val parts: JSONArray = content.optJSONArray("parts") ?: continue
            for (p in 0 until parts.length()) {
                val part = parts.optJSONObject(p) ?: continue
                val chunk = part.optString("text", "")
                if (chunk.isNotEmpty()) text.append(chunk)
            }
        }
        return text.toString().takeIf { it.isNotBlank() }
    }

    /**
     * The text as it may be stored, or null when there is not enough of it to be worth keeping.
     *
     * Code fences are stripped because a model occasionally wraps plain prose in them, and they
     * would otherwise render literally. The result is capped rather than rejected so a long answer
     * is still usable.
     */
    fun sanitize(raw: String?): String? {
        if (raw.isNullOrBlank()) return null
        val cleaned = stripFences(raw)
            .lineSequence()
            .joinToString("\n") { it.trim() }
            .replace(Regex("\n{3,}"), "\n\n")
            .trim()
        if (cleaned.length < MIN_CHARS) return null
        return if (cleaned.length <= MAX_CHARS) cleaned else cleaned.take(MAX_CHARS).trimEnd()
    }

    /**
     * The subject headings as they may be stored: trimmed, blank-free, de-duplicated and bounded.
     *
     * A heading is capped rather than dropped, because a slightly long heading is still a heading,
     * but a list longer than [MAX_THEMES] is truncated — a card that lists twenty subjects has
     * stopped summarising. De-duplication is case-insensitive so a model repeating "Biology" and
     * "biology" does not produce a visibly duplicated list.
     */
    fun sanitizeThemes(raw: JSONArray?): List<String> {
        if (raw == null || raw.length() == 0) return emptyList()
        val seen = LinkedHashSet<String>()
        for (i in 0 until raw.length()) {
            val value = raw.optString(i, "").trim().replace(Regex("\\s+"), " ")
            if (value.isEmpty()) continue
            val bounded = if (value.length <= MAX_THEME_CHARS) value else value.take(MAX_THEME_CHARS).trimEnd()
            if (seen.none { it.equals(bounded, ignoreCase = true) }) seen.add(bounded)
            if (seen.size >= MAX_THEMES) break
        }
        return seen.toList()
    }

    /**
     * Removes the code fence a model occasionally wraps an answer in.
     *
     * The opening fence may carry a language tag — ` ```json ` — which is part of the fence, not part
     * of the answer. Leaving it behind would make the JSON unparseable, and the fenced document would
     * then be shown on the card as if it were prose: exactly the outcome the JSON path exists to
     * prevent. A stray fence in text that is not fenced at all is still removed, because it would
     * otherwise render literally.
     */
    private fun stripFences(raw: String): String {
        val trimmed = raw.trim()
        if (!trimmed.startsWith("```")) return trimmed.replace("```", "").trim()
        var body = trimmed.removePrefix("```")
        val newline = body.indexOf('\n')
        if (newline >= 0) {
            body = body.substring(newline + 1)
        } else {
            // A single-line fence such as ```` ```json{…}``` ````: drop the tag up to the payload.
            val start = body.indexOfFirst { it == '{' || it == '[' }
            if (start >= 0) body = body.substring(start)
        }
        val end = body.lastIndexOf("```")
        if (end >= 0) body = body.substring(0, end)
        return body.trim()
    }

    /**
     * True when [overview] can be shown for [language] without generating anything.
     *
     * The prompt version must match, so a text written by an older prompt is regenerated rather
     * than displayed as if the current prompt had produced it.
     *
     * [contextFingerprint] is supplied when the text would have to be generated from a **search**
     * rather than from a catalogue record — that is, when the book has no catalogue match. In that
     * case the cached text must have been generated for the same question; a text answering a
     * different question is not reusable. An empty fingerprint means "this path does not depend on
     * one", which is the catalogue path and every cached text written before the search existed.
     */
    fun isUsableFor(
        overview: BookIntelOverview?,
        language: String,
        contextFingerprint: String = "",
    ): Boolean =
        overview != null &&
            overview.language.equals(language, ignoreCase = true) &&
            overview.promptVersion == VERSION &&
            overview.text.isNotBlank() &&
            (contextFingerprint.isEmpty() || overview.contextFingerprint == contextFingerprint)

    /**
     * Keeps the cached overviews bounded.
     *
     * A reader who tries many languages must not grow the library record without limit, so only the
     * most recently generated texts are kept. The newest is always retained.
     */
    fun prune(overviews: List<BookIntelOverview>, keep: Int = MAX_CACHED): List<BookIntelOverview> {
        if (overviews.size <= keep) return overviews
        return overviews.sortedByDescending { it.generatedAt }.take(keep)
    }

    /** How many languages one book may cache an overview for. */
    const val MAX_CACHED = 3
}
