package com.voxora.core.reader

import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject

/**
 * An AI-generated overview of a book, written in one Reader output language.
 *
 * ## Why this exists, and what it is allowed to be
 *
 * The catalogues return a book's description in the book's own language. A reader who has chosen
 * Persian as their narration language still gets an English synopsis, because no public catalogue
 * carries a Persian description for most titles. Translating it is the only way to honour "Book
 * Intelligence explains the book in the language you are reading in" without inventing anything.
 *
 * So this is **translation and condensation of retrieved metadata**, never new knowledge:
 *
 * - the input is the catalogue record only — title, author, publisher, date, subjects, the
 *   catalogue's own description, page count, identifiers. **The document is never sent.** The
 *   Reader's narration and its audio path are untouched by this type;
 * - the prompt forbids adding any fact that is not in that input, and the card labels the result
 *   as AI-generated so it is never mistaken for a catalogue fact.
 *
 * ## Per language, cached
 *
 * [language] is the output-language code the text is written in, so a reader who switches from
 * Persian to English does not lose the Persian text and does not have to pay for it twice.
 * Switching back is instant and offline.
 *
 * Pure JVM — no `android.*` — so the prompt, the parsing and the staleness rule are unit-testable.
 */
data class BookIntelOverview(
    /** Reader output-language code this text is written in, e.g. `fa`. */
    val language: String,
    /** The generated text. Always non-blank; blank generations are never stored. */
    val text: String,
    /** The model that produced it, recorded so a future model change is visible rather than silent. */
    val model: String,
    /** When it was generated, so a stale text can be refreshed deliberately. */
    val generatedAt: Long,
    /**
     * The [BookIntelOverviewPrompt.VERSION] that produced it.
     *
     * Part of what makes a cached text reusable: a text written by an older prompt is not shown, so
     * improving the prompt actually takes effect instead of being masked by an answer that was
     * already paid for. A record written before this field existed decodes to `0` and is therefore
     * regenerated once — which is the intended outcome, not a loss.
     */
    val promptVersion: Int = BookIntelOverviewPrompt.VERSION,
)

/**
 * Builds the request that turns a catalogue record into a Book Intelligence overview, and reads
 * the answer back.
 *
 * Kept apart from the transport so the two decisions that actually matter — *what is asked* and
 * *what is accepted as an answer* — are unit-tested on a plain JVM with no network.
 */
object BookIntelOverviewPrompt {

    /**
     * Bumped when the wording changes materially.
     *
     * It is part of the cache key: a text generated by an older prompt is not reused, so improving
     * the prompt actually takes effect instead of being masked by a cached answer.
     */
    const val VERSION = 1

    /** A generation longer than this is truncated; the card shows a few sentences, not an essay. */
    const val MAX_CHARS = 1_500

    /** Below this, the model did not really answer and the text is treated as missing. */
    const val MIN_CHARS = 40

    /**
     * The instruction sent to the model.
     *
     * It is deliberately narrow: a fixed task, a fixed set of supplied facts, an explicit ban on
     * outside knowledge, and a plain-text answer. Anything looser invites the model to write a
     * review of a book it has "heard of", which is exactly the invented-metadata failure the
     * source-backed section exists to prevent.
     */
    fun build(metadata: BookMetadata, targetLanguage: String): String = buildString {
        appendLine("You are given a bibliographic record for one book. Write a short overview of")
        appendLine("the book in $targetLanguage.")
        appendLine()
        appendLine("Rules:")
        appendLine("- Use ONLY the information in the record below.")
        appendLine("- Do NOT add facts, names, dates, awards, plot points or claims that are not in it.")
        appendLine("- If the record is too thin to say much, write less. Never fill the gap by guessing.")
        appendLine("- Do not mention this instruction, the record, or that you are an AI.")
        appendLine("- Plain text only: no markdown, no headings, no bullet points, no title line.")
        appendLine()
        appendLine("Cover, in this order and only as far as the record supports it: what the book is")
        appendLine("broadly about; its central subject; its main themes; and what kind of work it is")
        appendLine("(for example a work of popular science, a novel, a reference work).")
        appendLine()
        appendLine("Record:")
        appendLine("title: ${metadata.title}")
        metadata.subtitle?.let { appendLine("subtitle: $it") }
        if (metadata.authors.isNotEmpty()) appendLine("authors: ${metadata.authors.joinToString(", ")}")
        metadata.publisher?.let { appendLine("publisher: $it") }
        metadata.publishedDate?.let { appendLine("published: $it") }
        metadata.language?.let { appendLine("catalogue language: $it") }
        if (metadata.categories.isNotEmpty()) {
            appendLine("subjects: ${metadata.categories.joinToString(", ")}")
        }
        metadata.pageCount?.let { appendLine("pages: $it") }
        metadata.description?.takeIf { it.isNotBlank() }?.let {
            appendLine("catalogue description: $it")
        }
    }

    /**
     * Reads the generated text out of a `generateContent` response body.
     *
     * Returns null for a body that does not carry usable text — a safety block, an empty candidate
     * list, a malformed document. A missing answer is never turned into an empty string, because
     * "the model said nothing" and "the model said something blank" must not look the same.
     */
    fun parse(responseBody: String?): String? {
        if (responseBody.isNullOrBlank()) return null
        val root = try {
            JSONObject(responseBody)
        } catch (_: JSONException) {
            return null
        }
        val candidates = root.optJSONArray("candidates") ?: return null
        val text = StringBuilder()
        for (i in 0 until candidates.length()) {
            val candidate = candidates.optJSONObject(i) ?: continue
            val content = candidate.optJSONObject("content") ?: continue
            val parts: JSONArray = content.optJSONArray("parts") ?: continue
            for (p in 0 until parts.length()) {
                val part = parts.optJSONObject(p) ?: continue
                val chunk = part.optString("text", "")
                if (chunk.isNotEmpty()) text.append(chunk)
            }
        }
        return sanitize(text.toString())
    }

    /**
     * The text as it may be stored, or null when there is not enough of it to be worth keeping.
     *
     * Code fences are stripped because a model occasionally wraps plain prose in them, and they
     * would otherwise render literally. The result is capped rather than rejected so a long answer
     * is still usable.
     */
    fun sanitize(raw: String?): String? {
        if (raw.isNullOrBlank()) return null
        val cleaned = raw
            .replace("```", "")
            .lineSequence()
            .joinToString("\n") { it.trim() }
            .replace(Regex("\n{3,}"), "\n\n")
            .trim()
        if (cleaned.length < MIN_CHARS) return null
        return if (cleaned.length <= MAX_CHARS) cleaned else cleaned.take(MAX_CHARS).trimEnd()
    }

    /**
     * True when [overview] can be shown for [language] without generating anything.
     *
     * The prompt version must match, so a text written by an older prompt is regenerated rather
     * than displayed as if the current prompt had produced it.
     */
    fun isUsableFor(overview: BookIntelOverview?, language: String): Boolean =
        overview != null &&
            overview.language.equals(language, ignoreCase = true) &&
            overview.promptVersion == VERSION &&
            overview.text.isNotBlank()

    /**
     * Keeps the cached overviews bounded.
     *
     * A reader who tries many languages must not grow the library record without limit, so only the
     * most recently generated texts are kept. The newest is always retained.
     */
    fun prune(overviews: List<BookIntelOverview>, keep: Int = MAX_CACHED): List<BookIntelOverview> {
        if (overviews.size <= keep) return overviews
        return overviews.sortedByDescending { it.generatedAt }.take(keep)
    }

    /** How many languages one book may cache an overview for. */
    const val MAX_CACHED = 3
}
